module.exports = {
    DISCORD_BOT_TOKEN : "ODI5OTQwODE3NTY0OTI2MDAy.YG_cng.iPqmqyTSOoII7LMmX9h67I5oB0w",
    GITHUB_PERSONAL_ACCESS_TOKEN : "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",
    GITHUB_REPO_OWNER_USERNAME : "prakharsr"
}